#
# /etc/pacman.conf for to[no]ME! Linux ISO
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# Tonome custom repository
[tonome]
SigLevel = Optional TrustAll
Server = file:///repo/tonome/$arch

# Official Arch repositories
[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
