# systemd-boot entry for to[no]ME! Linux

title   to[no]ME! Linux
linux   /%INSTALL_DIR%/boot/vmlinuz-linux-tonome
initrd  /%INSTALL_DIR%/boot/initramfs-linux-tonome.img
options quiet splash rd.systemd.show_status=1 rd.udev.log_priority=3

title   to[no]ME! Linux (Safe Mode)
linux   /%INSTALL_DIR%/boot/vmlinuz-linux-tonome
initrd  /%INSTALL_DIR%/boot/initramfs-linux-tonome.img
options nomodeset quiet

title   to[no]ME! Linux (Debug)
linux   /%INSTALL_DIR%/boot/vmlinuz-linux-tonome
initrd  /%INSTALL_DIR%/boot/initramfs-linux-tonome.img
options debug systemd.log_level=debug
